version: 2
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.0.0'
    hostname: zookeeper
    ports:
      - '2181:2181/tcp'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  broker-1:
    image: 'confluentinc/cp-enterprise-kafka:5.1.0'
    hostname: broker-1
    links:
      - 'zookeeper:zookeeper'
    ports:
      - '9092:9092/tcp'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_BROKER_RACK=rack-a
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - KAFKA_ADVERTISED_HOST_NAME=129.156.113.127
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker-1:9092'
      - >-
        KAFKA_METRIC_REPORTERS=io.confluent.metrics.reporter.ConfluentMetricsReporter
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_JMX_PORT=9999
      - >-
        KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.rmi.port=9999
      - KAFKA_JMX_HOSTNAME=broker-1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - 'CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=broker-1:9092'
      - 'CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=zookeeper:2181'
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=1
      - CONFLUENT_METRICS_ENABLE=true
      - CONFLUENT_SUPPORT_CUSTOMER_ID=anonymous
  schema-registry:
    image: 'confluentinc/cp-schema-registry:5.1.0'
    hostname: schema-registry
    container_name: schema-registry
    links:
      - 'zookeeper:zookeeper'
      - 'broker-1:broker-1'
    ports:
      - '8081:8081/tcp'
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema_registry
      - 'SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181'
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN=*
      - 'SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,OPTIONS'
  kafka-manager:
    image: trivadisbds/kafka-manager
    hostname: kafka-manager
    links:
      - broker-1
    ports:
      - '9000:9000/tcp'
    environment:
      - 'ZK_HOSTS=129.156.113.127:2181'
      - APPLICATION_SECRET=letmein
  schema-registry-ui:
    image: landoop/schema-registry-ui
    hostname: schema-registry-ui
    ports:
      - '8002:8000/tcp'
    environment:
      - 'SCHEMAREGISTRY_URL=http://129.156.113.127:8081'
